-- Add detail column to cases table
ALTER TABLE cases ADD COLUMN IF NOT EXISTS detail JSONB;

-- Add structured column to reports table
ALTER TABLE reports ADD COLUMN IF NOT EXISTS structured JSONB;

-- Add indexes for performance
CREATE INDEX IF NOT EXISTS idx_cases_detail ON cases USING GIN (detail);
CREATE INDEX IF NOT EXISTS idx_reports_structured ON reports USING GIN (structured);

-- Comment on columns
COMMENT ON COLUMN cases.detail IS 'Structured case information: overview, facts, legal_elements, evidence';
COMMENT ON COLUMN reports.structured IS 'Structured report data generated by AI';
